build-and-push-to-ecr:
  stage: build
  variables: 
    AWS_DEFAULT_REGION: us-east-1
    CI_REGISTRY_IMAGE: 935370813358.dkr.ecr.us-east-1.amazonaws.com/cntf-ueransim-puppeteer
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    -  mkdir -p /kaniko/.docker
    -  echo "{\"credsStore\":\"ecr-login\"}" > /kaniko/.docker/config.json
    -  /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"